// Generated by gencpp from file beginner_tutorials/testMsg.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TESTMSG_H
#define BEGINNER_TUTORIALS_MESSAGE_TESTMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace beginner_tutorials
{
template <class ContainerAllocator>
struct testMsg_
{
  typedef testMsg_<ContainerAllocator> Type;

  testMsg_()
    : header()
    , str()
    , integer(0)  {
    }
  testMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , str(_alloc)
    , integer(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _str_type;
  _str_type str;

   typedef int64_t _integer_type;
  _integer_type integer;





  typedef boost::shared_ptr< ::beginner_tutorials::testMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::testMsg_<ContainerAllocator> const> ConstPtr;

}; // struct testMsg_

typedef ::beginner_tutorials::testMsg_<std::allocator<void> > testMsg;

typedef boost::shared_ptr< ::beginner_tutorials::testMsg > testMsgPtr;
typedef boost::shared_ptr< ::beginner_tutorials::testMsg const> testMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::testMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::testMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::testMsg_<ContainerAllocator1> & lhs, const ::beginner_tutorials::testMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.str == rhs.str &&
    lhs.integer == rhs.integer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::testMsg_<ContainerAllocator1> & lhs, const ::beginner_tutorials::testMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::testMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::testMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::testMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::testMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::testMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::testMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::testMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9038168108474b623204af1525717741";
  }

  static const char* value(const ::beginner_tutorials::testMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9038168108474b62ULL;
  static const uint64_t static_value2 = 0x3204af1525717741ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::testMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/testMsg";
  }

  static const char* value(const ::beginner_tutorials::testMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::testMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header \n"
"string str  \n"
"int64 integer \n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::beginner_tutorials::testMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::testMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.str);
      stream.next(m.integer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct testMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::testMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::testMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.str);
    s << indent << "integer: ";
    Printer<int64_t>::stream(s, indent + "  ", v.integer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TESTMSG_H
